site_name: xnemogcm documentation
site_url: https://xnemogcm.readthedocs.io
nav:
  - Get started:
      - Get started: index.md
  - Examples:
      - "open files / Datasets": examples/open_process_files.ipynb
      - "recombine files": examples/recombing_mesh_mask_domain_cfg.ipynb
      - "compute metrics": examples/compute_metrics.ipynb
  - API:
      - API: api.md
  - "For contributors":
      - "What's new": new.md
      - "Dev environment": dev.md
      - "Code of conduct": CODE_OF_CONDUCT.md
      - "GitHub repository": https://github.com/rcaneill/xnemogcm
theme: readthedocs
plugins:
  - mkdocs-jupyter:
      execute: true
      include_source: True
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
            docstring_style: numpy
            heading_level: 2
      default_handler: python
